### ISSUE TITLE
Clean up utility functions

### ISSUE THREAD

**Issue by jackie-scholl** [raptortech-js/ncf-web-contract-system#36]
The file main.js currently has a few general-ish utility functions that should be moved elsewhere. I would suggest creating a new file called utility.js, and moving the functions there. The particular functions I'm talking about are:
- `timeSince`
- `resizeArray`
- `arraysEqual`
- `testResizeArray`

It is _not_ in the scope of this issue to turn `testResizeArray` into a proper test. Here are some important tips:
- Make sure to follow the [Github Flow](https://guides.github.com/introduction/flow/); if you do your work in the main branch, Github will reject it
- If you have any JavaScript questions, you can ask me or look at the great [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference)
- Make sure to include `'use strict'` as the first line to enable [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)
- Remember to run the linter and tests frequently with `npm test`. If you get a linter error, it should include a link to an explanation of the linter rule and perhaps why it's useful. If you're still confused, or think it should be changed, create an issue here on Github or contact me.
- In particular, the linter is pretty picky about whitespace and it requires you to always use `const` or `let`, never `var`
- This project uses the [CommonJS](https://nodejs.org/docs/latest/api/modules.html) module system
- At the end of the file, you'll want to write a `module.exports` statements that might look something like this:

```
module.exports = {
  timeSince: timeSince,
  resizeArray: resizeArray
};
```
- Note that you do not need to export `arraysEqual` or `testResizeArray`, as they are only used internally
- You will also need to import the respective functions in `main.js`. That might look something like this:

```
const timeSince = require('./utility.js').timeSince;
const resizeArray = require('./utility.js').resizeArray;
```

**Comment by sawyerWeld** [comment]
This doesnt look too bad,  I'll get it done.
