### ISSUE TITLE
Google login OAuth2 Error

### ISSUE THREAD

**Issue by sawyerWeld** [raptortech-js/ncf-web-contract-system#49]
The following Error 400 appears when attempting to login:

Error: redirect_uri_mismatch

The JavaScript origin in the request, http://localhost:4243, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/784978983695-km7e0k6q09qmrmgk3r2aortu0oqdk2tk.apps.googleusercontent.com?project=784978983695 to update the authorized JavaScript origins.

**Comment by jackie-scholl** [comment]
Looks like you changed the port? It should be [http://localhost:4232](http://localhost:4232), I think.

**Comment by sawyerWeld** [comment]
Mine always opens to 4243 and its up to date with master

**Comment by jackie-scholl** [comment]
Ok so I fixed part but not all of this
